{% set version = "1.2.4" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/v{{ version }}.tar.gz
  sha256: 9161eee81fbf27934eac1bc0d26ad3b933a582721fa66fe87e930ff2e9867c52

build:
  number: 3
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - mkl-devel
    - cython
    - numpy
    - pip
  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - nosetests -v mkl_random
  requires:
    - nose
    - mkl-service
    - numpy >=1.14
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: http://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
  recipe-maintainers:
    - oleksandr-pavlyk
