{% set version = "1.0.4" %}

package:
    name: mkl_random
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl_random/archive/v{{version}}.tar.gz
    sha256: f328d76c30585e8ca63c7bced14185a0dc823bb27fbc11d05655c14fdabd46ed

build:
    number: 0
    skip: True  # [win and py27]
    ignore_run_exports:
      - blas

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
    host:
      - python
      - setuptools
      - mkl-devel
      - cython
      - numpy
    run:
      - python
      - mkl
      - {{ pin_compatible('numpy') }}

test:
    commands:
      - nosetests -v mkl_random
    requires:
      - nose
      - numpy >=1.14
    imports:
      - mkl_random
      - mkl_random.mklrand

about:
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    description:
        NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library,
        mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
    summary:
        Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
    recipe-maintainers:
      - oleksandr-pavlyk
