{% set version = "1.0.2" %}

package:
    name: mkl_random
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl_random/archive/v{{version}}.tar.gz
    sha256: 2270ef2834f6552850533aad01500d27c8e056f2cfbdbdb751593000aea1159e

build:
    number: 3
    skip: True  # [win and py27]

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
    host:
      - libblas
      - libcblas
      - python
      - setuptools
      - cython
      - numpy
    run:
      - python
      - {{ pin_compatible('numpy') }}

test:
    commands:
      - nosetests -v mkl_random
    requires:
      - nose
      - numpy >=1.14
    imports:

about:
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    description:
        NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library,
        mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
    summary:
        Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
    recipe-maintainers:
      - oleksandr-pavlyk
