{% set version = "1.2.9" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/v{{ version }}.tar.gz
  sha256: d55c08e0d38268cc0479dee022f8914b0f955194c15797358e7b86941b481124

build:
  number: 0
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - mkl-devel
    - cython
    - numpy
    - pip
  run:
    - python
    - mkl
    - numpy

test:
  commands:
    - pytest -v --pyargs mkl_random
  requires:
    - pytest  # [python_impl != "pypy"]
    - pytest <8  # [python_impl == "pypy"]
    - mkl-service
    - numpy
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: http://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
  recipe-maintainers:
    - oleksandr-pavlyk
