{% set version = "1.0.2" %}
{% set buildnumber = 0 %}


package:
    name: mkl_random
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl_random/archive/v{{version}}.tar.gz
    sha256: 2270ef2834f6552850533aad01500d27c8e056f2cfbdbdb751593000aea1159e

build:
    number: {{buildnumber}}
    skip: True  # [win and py27]

requirements:
    build:
      - python
      - setuptools
      - toolchain
      - mkl-devel
      - cython
      - numpy 1.11.*
    run:
      - python
      - mkl
      - numpy >=1.11

test:
    commands:
      - nosetests -v mkl_random
    requires:
      - nose
    imports:
      - mkl_random
      - mkl_random.mklrand

about:
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    description:
        NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library,
        mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
    summary:
        Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
    recipe-maintainers:
      - oleksandr-pavlyk
